---

- hosts: localhost
  vars:
    valuemaps:
      - mapname: "0:No, 1:Yes"
        mappings:
          - value: 0
            newvalue: "No"
          - value: 1
            newvalue: "Yes"
      - mapname: "SNMP (Type: CiscoEnvMonState)"
        mappings:
          - value: 1
            newvalue: normal
          - value: 2
            newvalue: warning
          - value: 3
            newvalue: critical
          - value: 4
            newvalue: shutdown
          - value: 5
            newvalue: notPresent
          - value: 6
            newvalue: notFunctioning
      - mapname: "SNMP (Type: TruthValue)"
        mappings:
          - value: 1
            newvalue: "True"
          - value: 2
            newvalue: "False"
      - mapname: "SNMP interface (dot3StatsDuplexStatus)"
        mappings:
          - value: 1
            newvalue: unknown
          - value: 2
            newvalue: halfDuplex
          - value: 3
            newvalue: fullDuplex
      - mapname: "SNMP interface (ifType)"
        mappings:
          - value: 1
            newvalue: other
          - value: 2
            newvalue: regular1822
          - value: 3
            newvalue: hdh1822
          - value: 4
            newvalue: ddnX25
          - value: 5
            newvalue: rfc877x25
          - value: 6
            newvalue: ethernetCsmacd
          - value: 7
            newvalue: iso88023Csmacd
          - value: 8
            newvalue: iso88024TokenBus
          - value: 9
            newvalue: iso88025TokenRing
          - value: 10
            newvalue: iso88026Man
          - value: 11
            newvalue: starLan
          - value: 12
            newvalue: proteon10Mbit
          - value: 13
            newvalue: proteon80Mbit
          - value: 14
            newvalue: hyperchannel
          - value: 15
            newvalue: fddi
          - value: 16
            newvalue: lapb
          - value: 17
            newvalue: sdlc
          - value: 18
            newvalue: ds1
          - value: 19
            newvalue: e1
          - value: 20
            newvalue: basicISDN
          - value: 21
            newvalue: primaryISDN
          - value: 22
            newvalue: propPointToPointSerial
          - value: 23
            newvalue: ppp
          - value: 24
            newvalue: softwareLoopback
          - value: 25
            newvalue: eon
          - value: 26
            newvalue: ethernet3Mbit
          - value: 27
            newvalue: nsip
          - value: 28
            newvalue: slip
          - value: 29
            newvalue: ultra
          - value: 30
            newvalue: ds3
          - value: 31
            newvalue: sip
          - value: 32
            newvalue: frameRelay
          - value: 33
            newvalue: rs232
          - value: 34
            newvalue: para
          - value: 35
            newvalue: arcnet
          - value: 36
            newvalue: arcnetPlus
          - value: 37
            newvalue: atm
          - value: 38
            newvalue: miox25
          - value: 39
            newvalue: sonet
          - value: 40
            newvalue: x25ple
          - value: 41
            newvalue: iso88022llc
          - value: 42
            newvalue: localTalk
          - value: 43
            newvalue: smdsDxi
          - value: 44
            newvalue: frameRelayService
          - value: 45
            newvalue: v35
          - value: 46
            newvalue: hssi
          - value: 47
            newvalue: hippi
          - value: 48
            newvalue: modem
          - value: 49
            newvalue: aal5
          - value: 50
            newvalue: sonetPath
          - value: 51
            newvalue: sonetVT
          - value: 52
            newvalue: smdsIcip
          - value: 53
            newvalue: propVirtual
          - value: 54
            newvalue: propMultiplexor
          - value: 55
            newvalue: ieee80212
          - value: 56
            newvalue: fibreChannel
          - value: 57
            newvalue: hippiInterface
          - value: 58
            newvalue: frameRelayInterconnect
          - value: 59
            newvalue: aflane8023
          - value: 60
            newvalue: aflane8025
          - value: 61
            newvalue: cctEmul
          - value: 62
            newvalue: fastEther
          - value: 63
            newvalue: isdn
          - value: 64
            newvalue: v11
          - value: 65
            newvalue: v36
          - value: 66
            newvalue: g703at64k
          - value: 67
            newvalue: g703at2mb
          - value: 68
            newvalue: qllc
          - value: 69
            newvalue: fastEtherFX
          - value: 70
            newvalue: channel
          - value: 71
            newvalue: ieee80211
          - value: 72
            newvalue: ibm370parChan
          - value: 73
            newvalue: escon
          - value: 74
            newvalue: dlsw
          - value: 75
            newvalue: isdns
          - value: 76
            newvalue: isdnu
          - value: 77
            newvalue: lapd
          - value: 78
            newvalue: ipSwitch
          - value: 79
            newvalue: rsrb
          - value: 80
            newvalue: atmLogical
          - value: 81
            newvalue: ds0
          - value: 82
            newvalue: ds0Bundle
          - value: 83
            newvalue: bsc
          - value: 84
            newvalue: async
          - value: 85
            newvalue: cnr
          - value: 86
            newvalue: iso88025Dtr
          - value: 87
            newvalue: eplrs
          - value: 88
            newvalue: arap
          - value: 89
            newvalue: propCnls
          - value: 90
            newvalue: hostPad
          - value: 91
            newvalue: termPad
          - value: 92
            newvalue: frameRelayMPI
          - value: 93
            newvalue: x213
          - value: 94
            newvalue: adsl
          - value: 95
            newvalue: radsl
          - value: 96
            newvalue: sdsl
          - value: 97
            newvalue: vdsl
          - value: 98
            newvalue: iso88025CRFPInt
          - value: 99
            newvalue: myrinet
          - value: 100
            newvalue: voiceEM
          - value: 101
            newvalue: voiceFXO
          - value: 102
            newvalue: voiceFXS
          - value: 103
            newvalue: voiceEncap
          - value: 104
            newvalue: voiceOverIp
          - value: 105
            newvalue: atmDxi
          - value: 106
            newvalue: atmFuni
          - value: 107
            newvalue: atmIma
          - value: 108
            newvalue: pppMultilinkBundle
          - value: 109
            newvalue: ipOverCdlc
          - value: 110
            newvalue: ipOverClaw
          - value: 111
            newvalue: stackToStack
          - value: 112
            newvalue: virtualIpAddress
          - value: 113
            newvalue: mpc
          - value: 114
            newvalue: ipOverAtm
          - value: 115
            newvalue: iso88025Fiber
          - value: 116
            newvalue: tdlc
          - value: 117
            newvalue: gigabitEthernet
          - value: 118
            newvalue: hdlc
          - value: 119
            newvalue: lapf
          - value: 120
            newvalue: v37
          - value: 121
            newvalue: x25mlp
          - value: 122
            newvalue: x25huntGroup
          - value: 123
            newvalue: trasnpHdlc
          - value: 124
            newvalue: interleave
          - value: 125
            newvalue: fast
          - value: 126
            newvalue: ip
          - value: 127
            newvalue: docsCableMaclayer
          - value: 128
            newvalue: docsCableDownstream
          - value: 129
            newvalue: docsCableUpstream
          - value: 130
            newvalue: a12MppSwitch
          - value: 131
            newvalue: tunnel
          - value: 132
            newvalue: coffee
          - value: 133
            newvalue: ces
          - value: 134
            newvalue: atmSubInterface
          - value: 135
            newvalue: l2vlan
          - value: 136
            newvalue: l3ipvlan
          - value: 137
            newvalue: l3ipxvlan
          - value: 138
            newvalue: digitalPowerline
          - value: 139
            newvalue: mediaMailOverIp
          - value: 140
            newvalue: dtm
          - value: 141
            newvalue: dcn
          - value: 142
            newvalue: ipForward
          - value: 143
            newvalue: msdsl
          - value: 144
            newvalue: ieee1394
          - value: 145
            newvalue: if-gsn
          - value: 146
            newvalue: dvbRccMacLayer
          - value: 147
            newvalue: dvbRccDownstream
          - value: 148
            newvalue: dvbRccUpstream
          - value: 149
            newvalue: atmVirtual
          - value: 150
            newvalue: mplsTunnel
          - value: 151
            newvalue: srp
          - value: 152
            newvalue: voiceOverAtm
          - value: 153
            newvalue: voiceOverFrameRelay
          - value: 154
            newvalue: idsl
          - value: 155
            newvalue: compositeLink
          - value: 156
            newvalue: ss7SigLink
          - value: 157
            newvalue: propWirelessP2P
          - value: 158
            newvalue: frForward
          - value: 159
            newvalue: rfc1483
          - value: 160
            newvalue: usb
          - value: 161
            newvalue: ieee8023adLag
          - value: 162
            newvalue: bgppolicyaccounting
          - value: 163
            newvalue: frf16MfrBundle
          - value: 164
            newvalue: h323Gatekeeper
          - value: 165
            newvalue: h323Proxy
          - value: 166
            newvalue: mpls
          - value: 167
            newvalue: mfSigLink
          - value: 168
            newvalue: hdsl2
          - value: 169
            newvalue: shdsl
          - value: 170
            newvalue: ds1FDL
          - value: 171
            newvalue: pos
          - value: 172
            newvalue: dvbAsiIn
          - value: 173
            newvalue: dvbAsiOut
          - value: 174
            newvalue: plc
          - value: 175
            newvalue: nfas
          - value: 176
            newvalue: tr008
          - value: 177
            newvalue: gr303RDT
          - value: 178
            newvalue: gr303IDT
          - value: 179
            newvalue: isup
          - value: 180
            newvalue: propDocsWirelessMaclayer
          - value: 181
            newvalue: propDocsWirelessDownstream
          - value: 182
            newvalue: propDocsWirelessUpstream
          - value: 183
            newvalue: hiperlan2
          - value: 184
            newvalue: propBWAp2Mp
          - value: 185
            newvalue: sonetOverheadChannel
          - value: 186
            newvalue: digitalWrapperOverheadChannel
          - value: 187
            newvalue: aal2
          - value: 188
            newvalue: radioMAC
          - value: 189
            newvalue: atmRadio
          - value: 190
            newvalue: imt
          - value: 191
            newvalue: mvl
          - value: 192
            newvalue: reachDSL
          - value: 193
            newvalue: frDlciEndPt
          - value: 194
            newvalue: atmVciEndPt
          - value: 195
            newvalue: opticalChannel
          - value: 196
            newvalue: opticalTransport
          - value: 197
            newvalue: propAtm
          - value: 198
            newvalue: voiceOverCable
          - value: 199
            newvalue: infiniband
          - value: 200
            newvalue: teLink
          - value: 201
            newvalue: q2931
          - value: 202
            newvalue: virtualTg
          - value: 203
            newvalue: sipTg
          - value: 204
            newvalue: sipSig
          - value: 205
            newvalue: docsCableUpstreamChannel
          - value: 206
            newvalue: econet
          - value: 207
            newvalue: pon155
          - value: 208
            newvalue: pon622
          - value: 209
            newvalue: bridge
          - value: 210
            newvalue: linegroup
          - value: 211
            newvalue: voiceEMFGD
          - value: 212
            newvalue: voiceFGDEANA
          - value: 213
            newvalue: voiceDID
          - value: 214
            newvalue: mpegTransport
          - value: 215
            newvalue: sixToFour
          - value: 216
            newvalue: gtp
          - value: 217
            newvalue: pdnEtherLoop1
          - value: 218
            newvalue: pdnEtherLoop2
          - value: 219
            newvalue: opticalChannelGroup
          - value: 220
            newvalue: homepna
          - value: 221
            newvalue: gfp
          - value: 222
            newvalue: ciscoISLvlan
          - value: 223
            newvalue: actelisMetaLOOP
          - value: 224
            newvalue: fcipLink
          - value: 225
            newvalue: rpr
          - value: 226
            newvalue: qam
          - value: 227
            newvalue: lmp
          - value: 228
            newvalue: cblVectaStar
          - value: 229
            newvalue: docsCableMCmtsDownstream
          - value: 230
            newvalue: adsl2
          - value: 231
            newvalue: macSecControlledIF
          - value: 232
            newvalue: macSecUncontrolledIF
          - value: 233
            newvalue: aviciOpticalEther
          - value: 234
            newvalue: atmbond
  tasks:
    - template:
        src: valuemap.xml.j2
        dest: "{{ item.mapname }}.xml"
      with_items: "{{ valuemaps }}"
